name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        PR_NUMBER: ${{github.event.number}}
      run: echo For PR Number $PR_NUMBER
