name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Standin for build step
      shell: |
        mkdir -p public
        cp *.html *.css *.js public
    - name: Pushdown to PR subdir
      env:
        PR_NUMBER: ${{github.event.number}}
      run: |
        mkdir -p PR-eview/${PR_NUMBER}
        mv public/* PR-eview/${PR_NUMBER}
        mv PR-eview public
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        keep_files: true
